// <auto-generated />
using MajestyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MajestyApi.Migrations
{
    [DbContext(typeof(MajestyApiContext))]
    [Migration("20220428222734_tutorial")]
    partial class tutorial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MajestyApi.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("MajestyApi.Models.Storie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Plot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Upvotes")
                        .HasColumnType("int");

                    b.Property<string>("Writer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Storie");
                });

            modelBuilder.Entity("MajestyApi.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Age = 46,
                            Email = "marcos.lee@gmail.com",
                            FirstName = "Marcos",
                            Grade = 3,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 2,
                            Age = 23,
                            Email = "miguel.tapanez@gmail.com",
                            FirstName = "Miguel",
                            Grade = 5,
                            LastName = "Tapanez"
                        },
                        new
                        {
                            ID = 3,
                            Age = 32,
                            Email = "miguel.fernandez@gmail.com",
                            FirstName = "Miguel",
                            Grade = 5,
                            LastName = "Fernandez"
                        },
                        new
                        {
                            ID = 4,
                            Age = 31,
                            Email = "juliet.lee@gmail.com",
                            FirstName = "Juliet",
                            Grade = 5,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 5,
                            Age = 44,
                            Email = "tedd.hernandez@gmail.com",
                            FirstName = "Tedd",
                            Grade = 6,
                            LastName = "Hernandez"
                        },
                        new
                        {
                            ID = 6,
                            Age = 17,
                            Email = "miguel.garcia@gmail.com",
                            FirstName = "Miguel",
                            Grade = 2,
                            LastName = "Garcia"
                        },
                        new
                        {
                            ID = 7,
                            Age = 45,
                            Email = "marcos.doe@gmail.com",
                            FirstName = "Marcos",
                            Grade = 3,
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = 8,
                            Age = 23,
                            Email = "carlos.lee@gmail.com",
                            FirstName = "Carlos",
                            Grade = 3,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 9,
                            Age = 52,
                            Email = "tedd.fernandez@gmail.com",
                            FirstName = "Tedd",
                            Grade = 5,
                            LastName = "Fernandez"
                        },
                        new
                        {
                            ID = 10,
                            Age = 14,
                            Email = "miguel.doe@gmail.com",
                            FirstName = "Miguel",
                            Grade = 6,
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = 11,
                            Age = 14,
                            Email = "juliet.stampton@gmail.com",
                            FirstName = "Juliet",
                            Grade = 2,
                            LastName = "Stampton"
                        },
                        new
                        {
                            ID = 12,
                            Age = 11,
                            Email = "juliet.hernandez@gmail.com",
                            FirstName = "Juliet",
                            Grade = 3,
                            LastName = "Hernandez"
                        },
                        new
                        {
                            ID = 13,
                            Age = 58,
                            Email = "marcos.doe@gmail.com",
                            FirstName = "Marcos",
                            Grade = 4,
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = 14,
                            Age = 32,
                            Email = "jhon.lee@gmail.com",
                            FirstName = "Jhon",
                            Grade = 2,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 15,
                            Age = 39,
                            Email = "miguel.fernandez@gmail.com",
                            FirstName = "Miguel",
                            Grade = 4,
                            LastName = "Fernandez"
                        },
                        new
                        {
                            ID = 16,
                            Age = 17,
                            Email = "brayan.lee@gmail.com",
                            FirstName = "Brayan",
                            Grade = 5,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 17,
                            Age = 25,
                            Email = "jhon.tapanez@gmail.com",
                            FirstName = "Jhon",
                            Grade = 4,
                            LastName = "Tapanez"
                        },
                        new
                        {
                            ID = 18,
                            Age = 20,
                            Email = "juliet.lee@gmail.com",
                            FirstName = "Juliet",
                            Grade = 3,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 19,
                            Age = 52,
                            Email = "jhon.lee@gmail.com",
                            FirstName = "Jhon",
                            Grade = 6,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 20,
                            Age = 31,
                            Email = "carlos.tapanez@gmail.com",
                            FirstName = "Carlos",
                            Grade = 4,
                            LastName = "Tapanez"
                        },
                        new
                        {
                            ID = 21,
                            Age = 40,
                            Email = "jhon.hernandez@gmail.com",
                            FirstName = "Jhon",
                            Grade = 4,
                            LastName = "Hernandez"
                        },
                        new
                        {
                            ID = 22,
                            Age = 29,
                            Email = "marcos.stampton@gmail.com",
                            FirstName = "Marcos",
                            Grade = 4,
                            LastName = "Stampton"
                        },
                        new
                        {
                            ID = 23,
                            Age = 11,
                            Email = "juliet.garcia@gmail.com",
                            FirstName = "Juliet",
                            Grade = 2,
                            LastName = "Garcia"
                        },
                        new
                        {
                            ID = 24,
                            Age = 43,
                            Email = "carlos.garcia@gmail.com",
                            FirstName = "Carlos",
                            Grade = 1,
                            LastName = "Garcia"
                        },
                        new
                        {
                            ID = 25,
                            Age = 15,
                            Email = "carlos.hernandez@gmail.com",
                            FirstName = "Carlos",
                            Grade = 6,
                            LastName = "Hernandez"
                        },
                        new
                        {
                            ID = 26,
                            Age = 34,
                            Email = "juliet.fernandez@gmail.com",
                            FirstName = "Juliet",
                            Grade = 1,
                            LastName = "Fernandez"
                        },
                        new
                        {
                            ID = 27,
                            Age = 38,
                            Email = "marcos.stampton@gmail.com",
                            FirstName = "Marcos",
                            Grade = 2,
                            LastName = "Stampton"
                        },
                        new
                        {
                            ID = 28,
                            Age = 51,
                            Email = "juliet.garcia@gmail.com",
                            FirstName = "Juliet",
                            Grade = 5,
                            LastName = "Garcia"
                        },
                        new
                        {
                            ID = 29,
                            Age = 36,
                            Email = "juliet.tapanez@gmail.com",
                            FirstName = "Juliet",
                            Grade = 6,
                            LastName = "Tapanez"
                        },
                        new
                        {
                            ID = 30,
                            Age = 12,
                            Email = "brayan.stampton@gmail.com",
                            FirstName = "Brayan",
                            Grade = 3,
                            LastName = "Stampton"
                        },
                        new
                        {
                            ID = 31,
                            Age = 50,
                            Email = "carlos.lee@gmail.com",
                            FirstName = "Carlos",
                            Grade = 3,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 32,
                            Age = 54,
                            Email = "miguel.doe@gmail.com",
                            FirstName = "Miguel",
                            Grade = 4,
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = 33,
                            Age = 32,
                            Email = "brayan.stampton@gmail.com",
                            FirstName = "Brayan",
                            Grade = 2,
                            LastName = "Stampton"
                        },
                        new
                        {
                            ID = 34,
                            Age = 45,
                            Email = "marcos.garcia@gmail.com",
                            FirstName = "Marcos",
                            Grade = 5,
                            LastName = "Garcia"
                        },
                        new
                        {
                            ID = 35,
                            Age = 45,
                            Email = "marcos.garcia@gmail.com",
                            FirstName = "Marcos",
                            Grade = 1,
                            LastName = "Garcia"
                        },
                        new
                        {
                            ID = 36,
                            Age = 38,
                            Email = "jhon.doe@gmail.com",
                            FirstName = "Jhon",
                            Grade = 3,
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = 37,
                            Age = 22,
                            Email = "marcos.hernandez@gmail.com",
                            FirstName = "Marcos",
                            Grade = 3,
                            LastName = "Hernandez"
                        },
                        new
                        {
                            ID = 38,
                            Age = 56,
                            Email = "juliet.lee@gmail.com",
                            FirstName = "Juliet",
                            Grade = 6,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 39,
                            Age = 28,
                            Email = "brayan.stampton@gmail.com",
                            FirstName = "Brayan",
                            Grade = 1,
                            LastName = "Stampton"
                        },
                        new
                        {
                            ID = 40,
                            Age = 30,
                            Email = "miguel.doe@gmail.com",
                            FirstName = "Miguel",
                            Grade = 5,
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = 41,
                            Age = 15,
                            Email = "marcos.doe@gmail.com",
                            FirstName = "Marcos",
                            Grade = 2,
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = 42,
                            Age = 59,
                            Email = "jhon.stampton@gmail.com",
                            FirstName = "Jhon",
                            Grade = 3,
                            LastName = "Stampton"
                        },
                        new
                        {
                            ID = 43,
                            Age = 18,
                            Email = "brayan.lee@gmail.com",
                            FirstName = "Brayan",
                            Grade = 5,
                            LastName = "Lee"
                        },
                        new
                        {
                            ID = 44,
                            Age = 29,
                            Email = "juliet.tapanez@gmail.com",
                            FirstName = "Juliet",
                            Grade = 3,
                            LastName = "Tapanez"
                        },
                        new
                        {
                            ID = 45,
                            Age = 43,
                            Email = "brayan.garcia@gmail.com",
                            FirstName = "Brayan",
                            Grade = 3,
                            LastName = "Garcia"
                        },
                        new
                        {
                            ID = 46,
                            Age = 39,
                            Email = "marcos.fernandez@gmail.com",
                            FirstName = "Marcos",
                            Grade = 3,
                            LastName = "Fernandez"
                        },
                        new
                        {
                            ID = 47,
                            Age = 58,
                            Email = "marcos.stampton@gmail.com",
                            FirstName = "Marcos",
                            Grade = 1,
                            LastName = "Stampton"
                        },
                        new
                        {
                            ID = 48,
                            Age = 15,
                            Email = "jhon.stampton@gmail.com",
                            FirstName = "Jhon",
                            Grade = 5,
                            LastName = "Stampton"
                        },
                        new
                        {
                            ID = 49,
                            Age = 30,
                            Email = "jhon.tapanez@gmail.com",
                            FirstName = "Jhon",
                            Grade = 1,
                            LastName = "Tapanez"
                        },
                        new
                        {
                            ID = 50,
                            Age = 24,
                            Email = "jhon.hernandez@gmail.com",
                            FirstName = "Jhon",
                            Grade = 1,
                            LastName = "Hernandez"
                        });
                });

            modelBuilder.Entity("MajestyApi.Models.Tutorial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tutorial");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Lee",
                            Published = true,
                            Title = "Brayan"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Garcia",
                            Published = true,
                            Title = "Jhon"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Fernandez",
                            Published = true,
                            Title = "Juliet"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Tapanez",
                            Published = true,
                            Title = "Juliet"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Tapanez",
                            Published = true,
                            Title = "Tedd"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Fernandez",
                            Published = false,
                            Title = "Tedd"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Garcia",
                            Published = false,
                            Title = "Carlos"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Fernandez",
                            Published = false,
                            Title = "Marcos"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Garcia",
                            Published = false,
                            Title = "Marcos"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Garcia",
                            Published = true,
                            Title = "Jhon"
                        },
                        new
                        {
                            ID = 11,
                            Description = "Tapanez",
                            Published = true,
                            Title = "Tedd"
                        },
                        new
                        {
                            ID = 12,
                            Description = "Hernandez",
                            Published = true,
                            Title = "Miguel"
                        },
                        new
                        {
                            ID = 13,
                            Description = "Garcia",
                            Published = false,
                            Title = "Brayan"
                        },
                        new
                        {
                            ID = 14,
                            Description = "Stampton",
                            Published = false,
                            Title = "Miguel"
                        },
                        new
                        {
                            ID = 15,
                            Description = "Hernandez",
                            Published = false,
                            Title = "Juliet"
                        },
                        new
                        {
                            ID = 16,
                            Description = "Hernandez",
                            Published = true,
                            Title = "Juliet"
                        },
                        new
                        {
                            ID = 17,
                            Description = "Doe",
                            Published = false,
                            Title = "Juliet"
                        },
                        new
                        {
                            ID = 18,
                            Description = "Stampton",
                            Published = false,
                            Title = "Tedd"
                        },
                        new
                        {
                            ID = 19,
                            Description = "Garcia",
                            Published = true,
                            Title = "Tedd"
                        },
                        new
                        {
                            ID = 20,
                            Description = "Fernandez",
                            Published = true,
                            Title = "Carlos"
                        },
                        new
                        {
                            ID = 21,
                            Description = "Tapanez",
                            Published = false,
                            Title = "Carlos"
                        },
                        new
                        {
                            ID = 22,
                            Description = "Garcia",
                            Published = false,
                            Title = "Juliet"
                        },
                        new
                        {
                            ID = 23,
                            Description = "Lee",
                            Published = false,
                            Title = "Juliet"
                        },
                        new
                        {
                            ID = 24,
                            Description = "Doe",
                            Published = false,
                            Title = "Jhon"
                        },
                        new
                        {
                            ID = 25,
                            Description = "Tapanez",
                            Published = false,
                            Title = "Marcos"
                        },
                        new
                        {
                            ID = 26,
                            Description = "Tapanez",
                            Published = true,
                            Title = "Jhon"
                        },
                        new
                        {
                            ID = 27,
                            Description = "Lee",
                            Published = true,
                            Title = "Jhon"
                        },
                        new
                        {
                            ID = 28,
                            Description = "Doe",
                            Published = true,
                            Title = "Carlos"
                        },
                        new
                        {
                            ID = 29,
                            Description = "Doe",
                            Published = true,
                            Title = "Miguel"
                        },
                        new
                        {
                            ID = 30,
                            Description = "Hernandez",
                            Published = false,
                            Title = "Tedd"
                        },
                        new
                        {
                            ID = 31,
                            Description = "Lee",
                            Published = true,
                            Title = "Miguel"
                        },
                        new
                        {
                            ID = 32,
                            Description = "Doe",
                            Published = false,
                            Title = "Marcos"
                        },
                        new
                        {
                            ID = 33,
                            Description = "Tapanez",
                            Published = false,
                            Title = "Juliet"
                        },
                        new
                        {
                            ID = 34,
                            Description = "Doe",
                            Published = true,
                            Title = "Miguel"
                        },
                        new
                        {
                            ID = 35,
                            Description = "Lee",
                            Published = true,
                            Title = "Tedd"
                        },
                        new
                        {
                            ID = 36,
                            Description = "Garcia",
                            Published = false,
                            Title = "Miguel"
                        },
                        new
                        {
                            ID = 37,
                            Description = "Fernandez",
                            Published = true,
                            Title = "Jhon"
                        },
                        new
                        {
                            ID = 38,
                            Description = "Garcia",
                            Published = false,
                            Title = "Brayan"
                        },
                        new
                        {
                            ID = 39,
                            Description = "Tapanez",
                            Published = false,
                            Title = "Marcos"
                        },
                        new
                        {
                            ID = 40,
                            Description = "Hernandez",
                            Published = true,
                            Title = "Tedd"
                        },
                        new
                        {
                            ID = 41,
                            Description = "Stampton",
                            Published = false,
                            Title = "Marcos"
                        },
                        new
                        {
                            ID = 42,
                            Description = "Garcia",
                            Published = true,
                            Title = "Jhon"
                        },
                        new
                        {
                            ID = 43,
                            Description = "Tapanez",
                            Published = false,
                            Title = "Marcos"
                        },
                        new
                        {
                            ID = 44,
                            Description = "Hernandez",
                            Published = false,
                            Title = "Jhon"
                        },
                        new
                        {
                            ID = 45,
                            Description = "Fernandez",
                            Published = false,
                            Title = "Carlos"
                        },
                        new
                        {
                            ID = 46,
                            Description = "Hernandez",
                            Published = true,
                            Title = "Marcos"
                        },
                        new
                        {
                            ID = 47,
                            Description = "Tapanez",
                            Published = false,
                            Title = "Tedd"
                        },
                        new
                        {
                            ID = 48,
                            Description = "Hernandez",
                            Published = false,
                            Title = "Carlos"
                        },
                        new
                        {
                            ID = 49,
                            Description = "Fernandez",
                            Published = true,
                            Title = "Brayan"
                        },
                        new
                        {
                            ID = 50,
                            Description = "Doe",
                            Published = true,
                            Title = "Carlos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
